### ISSUE TITLE
/loot not sending PM

### ISSUE THREAD

**Issue by fclaussen** [Galarzaa90/NabBot#22] opened 2017-06-15 23:12 UTC
While testing this feature, it displays the total amount on the general channel, but it says it sent a PM with detailed information. That PM never arrived. I saw this on my cmd.

![nabbot](https://user-images.githubusercontent.com/1021860/27205399-eecd1f74-5206-11e7-89f4-1155baeb3a60.png)

**Comment by Galarzaa90** [comment] 2017-06-16 00:00
What's the name of the image you're using? Is it happening with any image or just that one?

**Comment by fclaussen** [comment] 2017-06-16 00:15
Any image

**Comment by fclaussen** [comment] 2017-06-16 00:22
![unknown](https://user-images.githubusercontent.com/1021860/27206871-a78ed49a-5210-11e7-9530-a1183ac8329a.png)

Use this one as an example

**Comment by Galarzaa90** [comment] 2017-06-16 00:29
![image](https://user-images.githubusercontent.com/12865379/27206988-0ee2625e-51f0-11e7-8e29-1599302d2f76.png)
It worked fine for me, I assumed you're using **master**? Cause that's what I tested it on.

**Comment by fclaussen** [comment] 2017-06-16 00:36
I'm using master. On a fresh server

**Comment by fclaussen** [comment] 2017-06-16 00:37
If you are willing, I can add you to it as it's a test server and you can see for yourself

**Comment by fclaussen** [comment] 2017-06-16 00:41
Just tested the rewrite.

This worked on the rewrite, but not on the master

**Comment by Galarzaa90** [comment] 2017-06-16 00:47
I'm thinking it's maybe a combination of using the master branch on python 3.6
When I tested I used the master branch on python 3.4.

Gonna test that now.

**Comment by Galarzaa90** [comment] 2017-06-16 01:56
Confirmed, this happens only on the master branch, when using python 3.6. It is probably related to this:
https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep529

I couldn't fix it, for now.

**Comment by CuJo38** [comment] 2018-02-28 18:25
Yea I was just going to inquire about the same issue. This is probably a really dumb question but I had enough difficulty setting up the bot to run that I don't want to risk losing the into that it has for the people in my discord..  but I'm assuming this issue is caused by the newer versions of python? would simply uninstalling the version of python on my computer (whatever newest was in last month) and installing the 3.4 allow the loot PM to send and keep all the information safe so people don't need to re-add their chars?

**Comment by Galarzaa90** [comment] 2018-02-28 18:33
Yes @CuJo38, all the user information is in the database file called `users.db` and it's not affected at all by your Python version.

I should note that I'm going to drop support for Python 3.4 and 3.5 soon :tm:... But I haven't had much time lately.
This issue will be fixed when upgrading to python 3.6.

**Comment by Galarzaa90** [comment] 2018-03-09 06:20
I merged rewrite into master, support for Python versions under 3.6 has been dropped, so this bug is not reproducible anymore.

**Closed by Galarzaa90** 2018-03-09 06:20 UTC
Labels: bug, help wanted
