### ISSUE TITLE
[SOLVED] ERROR: get_recent_news: network error.

### ISSUE THREAD

**Issue by latocheski** [Galarzaa90/NabBot#112] opened 2018-07-12 14:52 UTC
I recently installed it here and am having this error, I followed the installation steps and the error persists!

ERROR: get_recent_news: network error.

The PY version is 3.6.

I was running that on VPS server.
![image](https://user-images.githubusercontent.com/26653089/42642399-cc0fa5b8-85c4-11e8-9186-e14d3c9bf5fb.png)

**Comment by latocheski** [comment] 2018-07-12 15:14
![image](https://user-images.githubusercontent.com/26653089/42642372-b8ddbf8e-85c4-11e8-87b1-f646e0832341.png)

**Comment by latocheski** [comment] 2018-07-12 15:36
Solved, I just set up the VPS correctly.

**Comment by Galarzaa90** [comment] 2018-07-12 15:38
I was going to say I couldn't reproduce this bug. Guess it was a network issue?

Closing this issue.

**Closed by Galarzaa90** 2018-07-12 15:38 UTC
